spring:
  application:
      name:
          s19-spring-mvc-boot
  mvc:
    view:
      prefix:
        /WEB-INF/jsp/
      suffix:
        .jsp
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password: sa
    driverClassName: org.h2.Driver