spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/note_db
    username: postgres
    password: admin
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update
    show-sql: true


springdoc:
  swagger-ui:
    path: /swagger-ui-index.html

server:
  port: 7777
